# Enable multiple mega's at one time
# Allowed values: true, false - Default: false
multipleMegas = false

# Enable mega evolution only for battles
# Allowed values: true, false - Default: false
battleModeOnly = false

# Makes it so that you need to have 200+ friendship in order to mega outside
# Allowed values: true, false - Default: false
friendshipMode = false

# Enables/Disables zMoves in game
# Allowed values: true, false - Default: true
zMoves = true

# Enables/Disables teralization in game
# Allowed values: true, false - Default: true
teralization = true

# Disables pokemons from dropping tera shards
# Allowed values: true, false - Default: false
disableTeraShardDrop = true

# Allows you to trade even if your pokemon is not in base form
# Allowed values: true, false - Default: false
tradeForm = false

# Enables etermax eternus forme
# Allowed values: true, false - Default: true
etermaxForme = true

# Enables/Disables Dmaxing in game
# Allowed values: true, false - Default: true
dynamax = true

# Enables/Disables Mega in game
# Allowed values: true, false - Default: true
mega = true

# Allows you to dynamax anywhere you dont need to be near the dynamax area
# Allowed values: true, false - Default: false
dynamaxAnywhere = false

# Range around a power spot where Dynamax is allowed
# Allowed range: 0 ~ 10000 - Default: 20
powerSpotRange = 20

# By how many times should the pokemon size increase when g/dmaxing
# Allowed range: 1 ~ 10000 - Default: 4
dynamaxScaleFactor = 4

#  Enable/Disable loading of showdown files from the mod, 
# note this means once you load the game and the showdown changes have been affected you disable
# this it will stop overwriting it ever load, this is for people who want to edit showdown 
# but can't since mega showdown keeps overriding the files
# Allowed values: true, false - Default: true
showdownFilesLoading = true

# Allows you to have multiple primals
# Allowed values: true, false - Default: true
multiplePrimals = true

# Enable/Disable mega pokemons form reverting when battle starts
# Allowed values: true, false - Default: true
revertMegas = true

