# Don't change this! Version used to track needed updates.
version = 0
tileStackingStyle = "HORIZONTAL"
easeInTiles = true
easeInDuration = 4
easeInAmount = 10
animateTileHover = true
hoverDelay = 4
tileWidth = 96
tileHeight = 96