loot_ball:
  generation:
    chance: 0.01125
    enabled: true
    chunk_cap: 1
    attempts: 2
  spawning:
    chance: 0.15
    cooldown:
      min: 6000
      max: 36000
    despawn:
      time: 24000
      enabled: true
    enabled: true
  defaults:
    multiplier: 1.0
    xp: 0
    despawn_tick: 0
    player_timer: 0
    uses: 1
  bonus:
    chance: 0.1
    multiplier: 2.0
    invisible: true
    enabled: true
  survival:
    drop:
      automatic: false
      enabled: false
    destroy_looted: false
  xp:
    enabled: true
  disabled:
    dimensions:
      generation:
        - eternal_starlight:starlight
        - academy:safari
      spawning:
        - eternal_starlight:starlight
        - academy:safari
      fishing: []
      archaeology: []
